### ISSUE TITLE
Broke my pc

### ISSUE THREAD

**Issue by gabaozin** [highoncarbs/automato#24]
Hi,

I hope you will be able to help me.

Doing the suggested command "pip install -r requirements.txt", after reboot, made my keyboard stop working and I noticed all packages from development (Python, pip, selenium, etc) either be deinstalled or downgraded to a much lower version.

I don't know to what extent changes have been made to my computer.

The terminal read:
Installing collected packages: SQLAlchemy, MarkupSafe, Mako, python-editor, six, python-dateutil, alembic, appdirs, attrs, regex, typed-ast, pathspec, Click, toml, black, certifi, pycparser, cffi, itsdangerous, Jinja2, Werkzeug, Flask, Flask-Cors, marshmallow, flask-marshmallow, Flask-SQLAlchemy, Flask-Migrate, greenlet, gevent, huey, idna, marshmallow-sqlalchemy, PyMySQL, redis, urllib3, requests, selenium

However, a pip uninstall "these packages" return a " WARNING: Skipping as it is not installed.

I did not had a system restore point.

I am on windows 10, on an ASUS N-550JK.

Any help will be much appreciated.

Top priority here is to make the laptop keyboard work please.

**Comment by TeddJohnson** [comment]
installing requirements via pip has ZERO effect on your keyboard.

**Comment by highoncarbs** [comment]
@TeddJohnson This is quite impossible . Also try creating a new virtual env for every python project

**Comment by TeddJohnson** [comment]
I think you meant to tell @gabaozin that it's quite impossible, I'm well aware that it couldn't happen.

**Comment by highoncarbs** [comment]
Yes , tagged you by mistake .
